import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../component/header";
import Sidebar from "../../component/sidebar";
import { ThemeProvider } from "@/component/themeProvider";
import TimerPopup from "@/component/timerpopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "todolife",
  description: "Generated by create next app",
  icons: { icon: "./tranicon-web.png" }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
          <Header />
          <Sidebar />
          {children}
          <TimerPopup />
      </body>
    </html>
  );
}
