
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../component/header";
import Sidebar from "../../component/sidebar";
import TimerPopup from "@/component/timerpopup";
import AosClientWrapper from "@/component/Aosanimation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "todolife",
  description: "Generated by create next app",
  icons: { icon: "./tranicon-web.png" }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }>
        <AosClientWrapper>
          <Header />
          <Sidebar />
          {children}
          <TimerPopup />
        </AosClientWrapper>
      </body>
    </html>
  );
}
